apiVersion: skaffold/v1
kind: Config
metadata:
  name: myapp
build:
  artifacts:
    - image: theater
      jib:  {}
deploy:
  kubectl:
    manifests:
      - infra/k8s.yaml

portForward: # This part is optional; add if want port-forwarding
  - resourceType: service #This too can change
    resourceName: theater-svc
    port: 8080
    localPort: 8080