apiVersion: skaffold/v1
kind: Config
metadata:
  name: theater-app
build:
  artifacts:
    - image: theater
      jib:  {}
deploy:
  kubectl:
    manifests:
      - infra/k8s.yaml

portForward:
  - resourceType: service
    resourceName: theater-svc
    port: 8080
    localPort: 8080