apiVersion: v1
kind: Service
metadata:
  name: theater-svc
spec:
  ports:
    - port: 8080
      name: http
      #nodePort: 30001
  type: NodePort
  selector:
    app: theater
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: theater-deploy
spec:
  selector:
    matchLabels:
      app: theater
  template:
    metadata:
      labels:
        app: theater
    spec:
      containers:
        - name: web
          image: theater:0.0.1-SNAPSHOT
          ports:
            - containerPort: 8080